export const ErrorCodes = {
  // Generic
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  RATE_LIMITED: 'RATE_LIMITED',

  // Auth
  EMAIL_TAKEN: 'EMAIL_TAKEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_BANNED: 'ACCOUNT_BANNED',
  ACCOUNT_INACTIVE: 'ACCOUNT_INACTIVE',
  INVALID_RESET_TOKEN: 'INVALID_RESET_TOKEN',
  RESET_TOKEN_EXPIRED: 'RESET_TOKEN_EXPIRED',

  // Taxonomy
  TOPIC_NOT_FOUND: 'TOPIC_NOT_FOUND',
  PERIOD_NOT_FOUND: 'PERIOD_NOT_FOUND',
  SLUG_TAKEN: 'SLUG_TAKEN',

  // Lessons
  LESSON_NOT_FOUND: 'LESSON_NOT_FOUND',
  LESSON_NOT_PUBLISHED: 'LESSON_NOT_PUBLISHED',

  // Quiz
  QUIZ_NOT_FOUND: 'QUIZ_NOT_FOUND',
  QUIZ_NOT_PUBLISHED: 'QUIZ_NOT_PUBLISHED',
  QUIZ_TIME_EXPIRED: 'QUIZ_TIME_EXPIRED',
  NO_OPEN_ATTEMPT: 'NO_OPEN_ATTEMPT',

  // Missions
  MISSION_NOT_FOUND: 'MISSION_NOT_FOUND',
  MISSION_NOT_COMPLETED: 'MISSION_NOT_COMPLETED',
  MISSION_ALREADY_CLAIMED: 'MISSION_ALREADY_CLAIMED',

  // AI
  AI_UNAVAILABLE: 'AI_UNAVAILABLE',

  // Publish validation
  PUBLISH_VALIDATION_FAILED: 'PUBLISH_VALIDATION_FAILED',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
